<a href="https://colab.research.google.com/github/kg-dev-20/ML-Repo/blob/main/AdenosisVSDuctal_Carcinoma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
zip_path = "/content/drive/MyDrive/BreaKHis 400x.zip"

In [ ]:
import zipfile

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/dataset")

In [ ]:
import os

print(os.listdir("/content/dataset/BreaKHis 400x"))

['.DS_Store', 'pt_vs_mc', 'ta_vs_lc', 'pt_vs_dc', 'f_vs_mc', 'f_vs_dc', 'ta_vs_mc', 'f_vs_lc', 'a_vs_mc', 'a_vs_pc', 'a_vs_dc', 'pt_vs_pc', 'pt_vs_lc', 'ta_vs_pc', 'ta_vs_dc', 'a_vs_lc', 'f_vs_pc']

In [ ]:
import pandas as pd
df = pd.read_excel("/content/dataset/BreaKHis 400x/a_vs_dc/a_vs_dc.xlsx")
df.head()

,Mean_cA3,Std_cA3,Max_cA3,Min_cA3,Mean_cH3,Std_cH3,Max_cH3,Min_cH3,Mean_cV3,Std_cV3,Max_cV3,Min_cV3,Mean_cD3,Std_cD3,Max_cD3,Min_cD3,cl
0,1483.029206,204.580785,1789.924188,795.924854,-0.082977,21.535856,181.029359,-161.301016,-0.053120,23.864543,145.056347,-124.998892,0.082291,11.092543,76.354064,-67.137667,a
1,1401.886129,117.249572,1706.516570,696.412115,-0.018967,16.626636,155.293735,-134.413364,0.102302,17.957409,125.031203,-90.074966,-0.061437,8.467896,59.493646,-54.912476,a
2,1402.079926,250.139426,1829.177816,740.230640,0.124357,23.399486,226.602009,-214.725498,0.015429,18.743445,154.414575,-152.009334,0.028038,9.596517,72.926070,-103.246219,a
3,1408.112904,207.157301,1786.680348,782.136015,0.086607,19.056373,158.985464,-112.927023,0.308821,19.651491,150.751889,-123.455379,0.036276,9.695331,62.412427,-54.342572,a
4,1494.448283,140.997447,1791.207328,726.079534,0.402126,24.314436,140.625422,-120.078283,-0.255319,22.162881,109.154933,-128.216438,-0.084587,10.927916,58.877331,-65.127167,a

In [ ]:
df['cl']=df['cl'].map({'dc':1,'a':0})
df.head()

,Mean_cA3,Std_cA3,Max_cA3,Min_cA3,Mean_cH3,Std_cH3,Max_cH3,Min_cH3,Mean_cV3,Std_cV3,Max_cV3,Min_cV3,Mean_cD3,Std_cD3,Max_cD3,Min_cD3,cl
0,1483.029206,204.580785,1789.924188,795.924854,-0.082977,21.535856,181.029359,-161.301016,-0.053120,23.864543,145.056347,-124.998892,0.082291,11.092543,76.354064,-67.137667,0
1,1401.886129,117.249572,1706.516570,696.412115,-0.018967,16.626636,155.293735,-134.413364,0.102302,17.957409,125.031203,-90.074966,-0.061437,8.467896,59.493646,-54.912476,0
2,1402.079926,250.139426,1829.177816,740.230640,0.124357,23.399486,226.602009,-214.725498,0.015429,18.743445,154.414575,-152.009334,0.028038,9.596517,72.926070,-103.246219,0
3,1408.112904,207.157301,1786.680348,782.136015,0.086607,19.056373,158.985464,-112.927023,0.308821,19.651491,150.751889,-123.455379,0.036276,9.695331,62.412427,-54.342572,0
4,1494.448283,140.997447,1791.207328,726.079534,0.402126,24.314436,140.625422,-120.078283,-0.255319,22.162881,109.154933,-128.216438,-0.084587,10.927916,58.877331,-65.127167,0

In [ ]:
df['cl'].value_counts()

cl
1    788
0    106
Name: count, dtype: int64

severe class imbalanced dataset

In [ ]:
df.shape

(894, 17)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df.drop('cl',axis=1)
y = df['cl']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train.shape

(715, 16)

In [ ]:
X_test.shape

(179, 16)

In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier(
    n_estimators=150,
    learning_rate=0.02,
    max_depth=4,
    eval_metric='logloss',
    random_state=42,
    subsample=0.8,
    scale_pos_weight=106/788
)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.02, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=150, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

Accuracy: 0.8659217877094972
              precision    recall  f1-score   support

           0       0.46      0.90      0.61        21
           1       0.99      0.86      0.92       158

    accuracy                           0.87       179
   macro avg       0.72      0.88      0.77       179
weighted avg       0.92      0.87      0.88       179

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, preds)

array([[ 19,   2],
       [ 22, 136]])

In [ ]:
import matplotlib.pyplot as plt
plt.plot(model.history.history['accuracy'],label='test_accuracy')
plt.legend()

AttributeError: 'XGBClassifier' object has no attribute 'history'

In [ ]:
from sklearn.metrics import f1_score
print(f1_score(y_test, preds))

In [ ]:
from sklearn.metrics import precision_recall_curve,auc
precision, recall, thresholds = precision_recall_curve(y_test, preds)
pr_auc = auc(recall, precision)
plt.plot(recall, precision, label=f'Precision-Recall Curve (AUC = {pr_auc:.2f})')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend()